import { Component, AfterViewInit, Input } from '@angular/core';
import { Chart, registerables } from 'chart.js';

Chart.register(...registerables);

@Component({
	selector: 'zigzag-chart',
	standalone: true,
	templateUrl: './zigzag-chart.component.html',
	styleUrls: ['./zigzag-chart.component.sass']
})
export class ZigzagChartComponent implements AfterViewInit {
	@Input() january: number = 10;
	@Input() february: number = 20;
	@Input() march: number = 35;
	@Input() april: number = 98;
	@Input() may: number = 1083;
	@Input() june: number = 98431;

	chart!: Chart<'line', number[], string>;

	ngAfterViewInit(): void {
		this.createChart();
	}

	createChart() {
		const ctx = document.getElementById('zigzagChart') as HTMLCanvasElement;

		if (!ctx) {
			console.error('Canvas element not found');
			return;
		}

		this.chart = new Chart(ctx, {
			type: 'line',
			data: {
				labels: ['January', 'February', 'March', 'April', 'May', 'June'],
				datasets: [{
					label: 'Monthly Data',
					data: [this.january, this.february, this.march, this.april, this.may, this.june],
					borderColor: '#E38A2B',
					backgroundColor: 'rgba(227, 138, 43, 0.2)',
					pointBackgroundColor: ['#E38A2B', '#384C6A', '#879BBB', '#E38A2B', '#384C6A', '#879BBB'],
					pointBorderColor: '#384C6A',
					pointRadius: 5,
					pointHoverRadius: 7,
					fill: false,
					tension: 0
				}]
			},
			options: {
				responsive: true,
				maintainAspectRatio: false,
				plugins: {
					legend: {
						position: 'bottom',
						labels: {
							color: '#B4B4B4',
							font: {
								size: 16,
								family: 'sans-serif',
								weight: 'lighter'
							},
							padding: 10
						}
					},
					title: {
						display: true,
						text: 'Total message generated by date',
						color: '#B4B4B4',
						font: {
							size: 20,
							family: 'sans-serif',
							weight: 'lighter'
						}
					}
				},
				scales: {
					y: {
						beginAtZero: true,
						ticks: {
							color: '#B4B4B4',
							font: {
								size: 14
							}
						}
					},
					x: {
						ticks: {
							color: '#B4B4B4',
							font: {
								size: 14
							}
						}
					}
				}
			}
		});
	}
}
